workspace:
  input_dir: ""
  output_dir: ""
  filetype: tsv
protein_markers:
  - Positivity - panCK* (MV Cell)
  - Positivity - CD45hu* (MV Cell)
  - Positivity - Vim* (MV Cell)
cell_types:
  "Immune cells":
    - 0
    - 1
    - null
sub_cell_types:
  "Immune cells":
    "PDPN+ Immune Cells":
      "Positivity - PDPN* (MV Cell)": 1
    "PDPN- Immune Cells":
      "Positivity - PDPN* (MV Cell)": 0
  "PDPN+ Immune Cells":
    "TGFb-Active PDPN+ Immune Cells":
      "Positivity - P-SMAD2* (MV - NUC)": 1
custom_colors:
  "Immune cells": "#fafafa"
  "Other cells": "#a3a3a3"
  "PDPN+ Immune Cells": "#ffd747"
  "TGFb-Active PDPN+ Immune Cells": "#14e136"
  "PDPN- Immune Cells": "#ee1b1b"
overwrite_existing_files: false
locally_save_anndata_files: true
spatial_plot:
  dpi: 300
  scatter_point_size: 50
  plot_options: all
  custom_plot: []